# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "v1.0.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "v2.14.1-0.20180928181052-40fb3b2c4120+incompatible"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
